kind: pipeline
type: docker
name: default

trigger:
  event:
    - push

steps:
  # App
  - name: tests-for-react-native-app
    image: cfreak/jest:latest
    commands:
      - cd src/app/
      - yarn
      - yarn test

  # Api
  - name: build-docker-codefirst-support-api
    image: plugins/docker
    settings:
      dockerfile: src/api/src/main/docker/Dockerfile-custom.native-micro
      context: src/api/
      registry: hub.codefirst.iut.uca.fr
      repo: hub.codefirst.iut.uca.fr/florent.marques/codefirst-support
      username:
        from_secret: SECRET_REGISTRY_USERNAME
      password:
        from_secret: SECRET_REGISTRY_PASSWORD

    # database container deployment
  - name: deploy-container-mongodb
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
        IMAGENAME: mongo
        CONTAINERNAME: codefirst-support-mongodb
        COMMAND: create
        # OVERWRITE: false
        PRIVATE: true
        ADMINS: samuelsirven
    # depends_on: [ build-docker-codefirst-support-api ]

  - name: deploy-codefirst-support-api-container
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
      IMAGENAME: hub.codefirst.iut.uca.fr/florent.marques/codefirst-support
      CONTAINERNAME: codefirst-support-api
      COMMAND: create
      OVERWRITE: true
      ADMINS: samuelsirven
    depends_on: [ build-docker-codefirst-support-api ]
