export const fonts = {
  // displaySmall: variant.titleSmall,
  // displayMedium: variant.titleMedium,
  // displayLarge: variant.titleLarge,
  // headlineSmall: variant.titleSmall,
  // headlineMedium: variant.titleMedium,
  // headlineLarge: variant.titleLarge,
  // titleSmall: variant.titleSmall ,
  // titleMedium: variant.titleMedium,
  // titleLarge: variant.titleLarge,
  // labelSmall: variant.bodySmall,
  // labelMedium: variant.bodyMedium,
  // labelLarge: variant.bodyLarge,
  // bodySmall: variant.bodySmall,
  // bodyMedium: variant.bodyMedium,
  // bodyLarge: variant.bodyLarge,
  // default: variant.default,
}
