# Command to use when starting development environment
# docker compose -f docker-compose-dev.yml up -d

version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: "codefirst-support-mongo"
    restart: always
    ports:
      - "27017:27017"
    networks:
      - codefirst-network
    volumes:
      - codefirst-support-volume:/data/db

networks:
  codefirst-network:
    name: codefirst_network
    driver: "bridge"

volumes:
  codefirst-support-volume:
