// users
const SET_LOGGED_USER = "SET_LOGGED_USER"
const SET_THEME: string = "SET_THEME"
// issues
const SET_ISSUES: string = "SET_ISSUES"
const SET_SELECTED_ISSUE: string = "SET_SELECTED_ISSUE"
const SET_ISSUE_LOADING: string = "SET_ISSUE_LOADING"

export {
  SET_THEME,
  SET_ISSUES,
  SET_SELECTED_ISSUE,
  SET_ISSUE_LOADING,
  SET_LOGGED_USER
}
