const FETCH_NOUNOURS: string = "FETCH_NOUNOURS"
const SET_THEME: string = "SET_THEME"
const SET_ISSUES: string = "SET_ISSUES"
const SET_SELECTED_ISSUE: string = "SET_SELECTED_ISSUE"

export {
  FETCH_NOUNOURS,
  SET_THEME,
  SET_ISSUES,
  SET_SELECTED_ISSUE
}
